### ISSUE TITLE
Set Title

### ISSUE THREAD

**Issue by cjsfj** [uniphil/merge-rss-php#1]
Love this package. Glad it's here as it's saved me a bunch of time.

Do you know of a quick way to set the title for the "merged" feed? I'm combing through simplexml docs but was hoping you knew something off hand. I'm trying to set the title and author of the merged feed.

Thanks,

CJ

**Comment by uniphil** [comment]
Oh that is lovely to hear! I originally created this on commission for a client who then disappeared and never paid haha, so it's nice that it's getting some use.

As for your question, I'm not a PHP programmer and I wrote this code two years ago, but I would start with [the literal XML template on lines 41-45](https://github.com/uniphil/merge-rss-php/blob/fa1333b594db0ad14ffa74c7f1dd370b886b62e5/src/merge_rss.php#L41-L45). Try adding `<title>` and `<author>` right inside the `<channel>` there? I think the items all just get appended, so hopefully it won't get eaten later.

**Comment by cjsfj** [comment]
Thanks! I think that the issue for me is that both of my source feeds have a `<title>` and `<author>` in the `<channel>` block, but somehow the merged feed has neither `<title>` nor `<author>`

I'll keep looking. Sounds like I might just need to figure out a way to add these elements after the merge.

**Comment by uniphil** [comment]
Oh, I think the merge completely ignores all the meta stuff from both feeds and puts nothing. Have a look at the lines I linked to, I think hard-coding them (or passing them as variable and inserting there) should work :)
